version: '3'

volumes:
  postgres_data:
    driver: local

services:
  postgres:
    container_name: communicator_development_db
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: development_db
      POSTGRES_USER: test-db-user
      POSTGRES_PASSWORD: test-db-password
    ports:
      - "5432:5432"